Refactor CAPD tests and automate CAPA tests
rancher-sandbox/rancher-turtles-e2e pull request #23
Opened 2024-04-09 12:58 UTC by valaparthvi

### What does this PR do?
1. Refactor the test by moving commonly required functions such as adding CAPIKubeadmProvider and editing rancher-turtles-controller-manager to turtles-operator.spec.ts
2. capd_cluster.spec.ts has been automatically formatted by the editor.
3. If local chart museum is not setup, use the official helm repo.
4. Automate CAPA tests

### Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #

### Checklist:
- [x] Squashed commits into logical changes
- [ ] Documentation
- [ ] GitHub Actions (if applicable) - [UI-RM_head_2.8](https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/8616110908)

### Special notes for your reviewer:

2024-04-12 06:44 UTC, cpinjani requested changes

2024-04-12 06:44 UTC, cpinjani commented on tests/cypress/latest/support/commands.ts
> +  cy.get('.ns-dropdown', { timeout: 12000 }).trigger('click');
```suggestion
  cy.getBySel('namespaces-dropdown').click();
```
Since cypress best practice to use _data-testid_, if available

2024-04-12 06:44 UTC, cpinjani commented on tests/cypress/latest/e2e/unit_tests/capd_cluster.spec.ts
> +        cy.contains('Deleting ' + clusterShort);
Not sure if this change is required for CAPD, usually it deletes quickly.
Can increase current timeout if though required.

2024-04-12 06:44 UTC, cpinjani commented on tests/cypress/latest/e2e/unit_tests/capa_setup.spec.ts
> +        it('Create CAPA namespace', () => {
Please add TODO, create function for namespace creation

2024-04-12 06:44 UTC, cpinjani commented on tests/cypress/latest/e2e/unit_tests/capa_setup.spec.ts
> +            cy.contains('Active aws v2.3.5 True', { timeout: 15000 });
Is version number check required..

2024-04-12 06:44 UTC, cpinjani commented on tests/cypress/latest/e2e/unit_tests/capa_cluster.spec.ts
> +      cy.contains('Provisioned ' + clusterShort, { timeout: timeout });
Could be checked by a shorter timeout here

2024-04-12 06:44 UTC, cpinjani commented on tests/cypress/latest/e2e/unit_tests/capa_cluster.spec.ts
> +  const repoUrl = "https://github.com/valaparthvi/rancher-turtles-fleet-example.git"
Can we use existing cluster names. If custom values required for region etc., can create 'rancher-turtles-e2e' fork
I will enable aws-janitor for cleanup.

2024-04-12 06:44 UTC, cpinjani commented on tests/cypress/latest/e2e/unit_tests/turtles_operator.spec.ts
>      it('Add local chartmuseum repo', () => {
```suggestion
    it('Add turtles repo', () => {
```

2024-04-12 09:35 UTC, valaparthvi commented on tests/cypress/latest/e2e/unit_tests/capa_setup.spec.ts
> +            cy.contains('Active aws v2.3.5 True', { timeout: 15000 });
Version check ensure that the provider is ready, version is only rendered if provider was successfully provisioned. We cannot simply rely on `Active` because in case of an error, the Active status does not change. I think a UI bug should be raised for this.

2024-04-12 09:37 UTC, valaparthvi commented on tests/cypress/latest/e2e/unit_tests/capa_cluster.spec.ts
> +  const repoUrl = "https://github.com/valaparthvi/rancher-turtles-fleet-example.git"
I changed the name to a generic one `turtles-qa-cluster`. Will that do?

2024-04-12 09:39 UTC, valaparthvi commented on tests/cypress/latest/e2e/unit_tests/capa_cluster.spec.ts
> +      cy.contains('Provisioned ' + clusterShort, { timeout: timeout });
Provisioning an EKS cluster is unpredictable in my opinion, it can take anywhere between 14-20 minutes, if the timeout is shorter, chances of test failure our higher. The current timeout is 20 minutes.

2024-04-12 09:41 UTC, cpinjani commented on tests/cypress/latest/e2e/unit_tests/capa_setup.spec.ts
> +            cy.contains('Active aws v2.3.5 True', { timeout: 15000 });
Please create a const for the string which we are asserting

2024-04-12 09:46 UTC, cpinjani commented on tests/cypress/latest/e2e/unit_tests/capa_cluster.spec.ts
> +      cy.contains('Provisioned ' + clusterShort, { timeout: timeout });
This check seems for 'Check cluster is not deleted after removal', so cluster must be already provisioned.
In fact, lets use `cy.checkCAPICluster(clusterShort);`

2024-04-12 10:15 UTC, valaparthvi commented on tests/cypress/latest/e2e/unit_tests/capa_cluster.spec.ts
> +      cy.contains('Provisioned ' + clusterShort, { timeout: timeout });
>This check seems for 'Check cluster is not deleted after removal', so cluster must be already provisioned.

My bad, you're right. I didn't notice which test you were referring to. Will fix that.

2024-04-15 09:03 UTC, cpinjani approved these changes

2024-04-15 15:16 UTC, valaparthvi commented
https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/8687314922

Passing GH action.

2024-04-15 15:16 UTC, merged