Use UI to create providers
rancher-sandbox/rancher-turtles-e2e pull request #32
Opened 2024-04-23 14:54 UTC by cpinjani

### What does this PR do?
Automate Creating CAPI providers by UI

### Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #27 

### Checklist:
- [x] GitHub Actions: https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/8801252565

2024-04-23 14:56 UTC, cpinjani commented on tests/cypress/latest/support/commands.ts
> -  cy.reload(true);
It was issue with v2.7, so not applicable now

2024-04-23 14:57 UTC, cpinjani commented on .github/workflows/master-e2e.yaml
> -      aws_b64encoded_credentials:
AWS Cloud credentials mapping with Turtles handles secret configuration

2024-04-24 10:28 UTC, valaparthvi requested changes

2024-04-24 10:28 UTC, valaparthvi commented on tests/cypress/latest/support/commands.ts
> +  cy.get('.vs__selected-options > span.vs__selected').eq(0).should('contain', namespace);
```suggestion
    cy.getBySel('name-ns-description-namespace').type(namespace + '{enter}');
```

2024-04-24 10:28 UTC, valaparthvi commented on tests/cypress/latest/support/commands.ts
> +    cy.get('.vs__selected-options > span.vs__selected').eq(1).should('contain', cloudCredentials);
```suggestion
    cy.getBySel('cluster-prov-select-credential').trigger('click');
    cy.contains(cloudCredentials).click();
```

2024-04-24 10:28 UTC, valaparthvi commented on tests/cypress/latest/support/commands.ts
> +  cy.get('.vs__selected-options > span.vs__selected').eq(0).should('contain', namespace);
```suggestion
      cy.getBySel('name-ns-description-namespace').type(namespace + '{enter}');
```

2024-04-24 10:28 UTC, valaparthvi commented on tests/cypress/latest/support/commands.ts
> +  cy.get('.vs__selected-options > span.vs__selected').eq(1).should('contain', type);
```suggestion
  cy.contains("Provider type").click();
  cy.contains(type).click();
```

2024-04-24 14:37 UTC, cpinjani commented
CI passed with latest changes: https://github.com/rancher-sandbox/rancher-turtles-e2e/actions/runs/8817437865

2024-04-24 14:38 UTC, merged